from models import BaseMonster
from moves import *

ALL_MONSTERS = [
    BaseMonster(
        u=0,
        v=0,
        w=48,
        h=32,
        name="サラマンド",
        type="ほのお",
        hp=114,
        attack=80,
        defense=70,
        speed=85,
        compatibility={
            "ノーマル": 1,
            "ほのお": 1,
            "みず": 2,
            "くさ": 0.5,
        },
        moves=[NORMAL_MOVES[0], FIRE_MOVES[0]],
    ),
    BaseMonster(
        u=0,
        v=32,
        w=48,
        h=32,
        name="サラマンドン",
        type1="ほのお",
        hp=153,
        attack=129,
        defense=105,
        speed=120,
        compatibility={
            "ノーマル": 1,
            "ほのお": 1,
            "みず": 2,
            "くさ": 0.5,
        },
        moves=[NORMAL_MOVES[1], FIRE_MOVES[1]],
    ),
    BaseMonster(
        u=48,
        v=0,
        w=48,
        h=32,
        name="セイレン",
        type="みず",
        hp=119,
        attack=70,
        defense=85,
        speed=63,
        compatibility={
            "ノーマル": 1,
            "ほのお": 0.5,
            "みず": 1,
            "くさ": 2,
        },
        moves=[NORMAL_MOVES[0], WATER_MOVES[0]],
    ),
    BaseMonster(
        u=48,
        v=32,
        w=48,
        h=32,
        name="セイレニスタ",
        type="みず",
        hp=154,
        attack=105,
        defense=125,
        speed=98,
        compatibility={
            "ノーマル": 1,
            "ほのお": 0.5,
            "みず": 1,
            "くさ": 2,
        },
        moves=[NORMAL_MOVES[1], WATER_MOVES[1]],
    ),
    BaseMonster(
        u=96,
        v=0,
        w=48,
        h=32,
        name="モリミン",
        type="くさ",
        hp=120,
        attack=85,
        defense=85,
        speed=65,
        compatibility={
            "ノーマル": 1,
            "ほのお": 2,
            "みず": 0.5,
            "くさ": 1,
        },
        moves=[NORMAL_MOVES[0], GRASS_MOVES[0]],
    ),
    BaseMonster(
        u=96,
        v=32,
        w=48,
        h=32,
        name="アロモリミン",
        type="くさ",
        hp=155,
        attack=120,
        defense=120,
        speed=100,
        compatibility={
            "ノーマル": 1,
            "ほのお": 2,
            "みず": 0.5,
            "くさ": 1,
        },
        moves=[NORMAL_MOVES[1], GRASS_MOVES[1]],
    ),
]
