from models import BaseMonster
from moves import *

ALL_MONSTERS = [
    BaseMonster(
        u=0,
        v=0,
        w=32,
        h=32,
        name="キミョウダネ",
        type1="くさ",
        type2="どく",
        hp=120,
        attack=85,
        defense=85,
        speed=65,
        compatibility={
            "ノーマル": 1,
            "ほのお": 2,
            "みず": 0.5,
            "くさ": 0.25,
            "ひこう": 2,
            "ドラゴン": 1,
            "どく": 1,
        },
        moves=[NORMAL_MOVES[0], GRASS_MOVES[0], GRASS_MOVES[3]],
    ),
    BaseMonster(
        u=0,
        v=32,
        w=32,
        h=32,
        name="キミョウソウ",
        type1="くさ",
        type2="どく",
        hp=135,
        attack=100,
        defense=100,
        speed=80,
        compatibility={
            "ノーマル": 1,
            "ほのお": 2,
            "みず": 0.5,
            "くさ": 0.25,
            "ひこう": 2,
            "ドラゴン": 1,
            "どく": 1,
        },
        moves=[NORMAL_MOVES[0], GRASS_MOVES[1], POIZON_MOVES[0], GRASS_MOVES[3]],
    ),
    BaseMonster(
        u=0,
        v=64,
        w=32,
        h=32,
        name="キミョウバナ",
        type1="くさ",
        type2="どく",
        hp=155,
        attack=120,
        defense=120,
        speed=100,
        compatibility={
            "ノーマル": 1,
            "ほのお": 2,
            "みず": 0.5,
            "くさ": 0.25,
            "ひこう": 2,
            "ドラゴン": 1,
            "どく": 1,
        },
        moves=[NORMAL_MOVES[1], GRASS_MOVES[2], POIZON_MOVES[1], GRASS_MOVES[3]],
    ),
    BaseMonster(
        u=32,
        v=0,
        w=32,
        h=32,
        name="サラマンダ",
        type1="ほのお",
        type2=None,
        hp=114,
        attack=80,
        defense=70,
        speed=85,
        compatibility={
            "ノーマル": 1,
            "ほのお": 0.5,
            "みず": 2,
            "くさ": 0.5,
            "ひこう": 1,
            "ドラゴン": 1,
            "どく": 1,
        },
        moves=[NORMAL_MOVES[0], FIRE_MOVES[0]],
    ),
    BaseMonster(
        u=32,
        v=32,
        w=32,
        h=32,
        name="サラマンド",
        type1="ほのお",
        type2=None,
        hp=133,
        attack=100,
        defense=85,
        speed=100,
        compatibility={
            "ノーマル": 1,
            "ほのお": 0.5,
            "みず": 2,
            "くさ": 0.5,
            "ひこう": 1,
            "ドラゴン": 1,
            "どく": 1,
        },
        moves=[NORMAL_MOVES[0], FIRE_MOVES[1], DRAGON_MOVES[0]],
    ),
    BaseMonster(
        u=32,
        v=64,
        w=32,
        h=32,
        name="サラマンドン",
        type1="ほのお",
        type2="ひこう",
        hp=153,
        attack=129,
        defense=105,
        speed=120,
        compatibility={
            "ノーマル": 1,
            "ほのお": 0.5,
            "みず": 2,
            "くさ": 0.25,
            "ひこう": 1,
            "ドラゴン": 1,
            "どく": 1,
        },
        moves=[FIRE_MOVES[2], FLY_MOVES[0], DRAGON_MOVES[1], FLY_MOVES[1]],
    ),
    BaseMonster(
        u=64,
        v=0,
        w=32,
        h=32,
        name="カネカメ",
        type1="みず",
        type2=None,
        hp=119,
        attack=70,
        defense=85,
        speed=63,
        compatibility={
            "ノーマル": 1,
            "ほのお": 0.5,
            "みず": 0.5,
            "くさ": 2,
            "ひこう": 1,
            "ドラゴン": 1,
            "どく": 1,
        },
        moves=[NORMAL_MOVES[0], WATER_MOVES[0]],
    ),
    BaseMonster(
        u=64,
        v=32,
        w=32,
        h=32,
        name="カメフライ",
        type1="みず",
        type2=None,
        hp=134,
        attack=85,
        defense=100,
        speed=78,
        compatibility={
            "ノーマル": 1,
            "ほのお": 0.5,
            "みず": 0.5,
            "くさ": 2,
            "ひこう": 1,
            "ドラゴン": 1,
            "どく": 1,
        },
        moves=[NORMAL_MOVES[0], WATER_MOVES[1]],
    ),
    BaseMonster(
        u=64,
        v=64,
        w=32,
        h=32,
        name="カメキャノン",
        type1="みず",
        type2=None,
        hp=154,
        attack=105,
        defense=125,
        speed=98,
        compatibility={
            "ノーマル": 1,
            "ほのお": 0.5,
            "みず": 0.5,
            "くさ": 2,
            "ひこう": 1,
            "ドラゴン": 1,
            "どく": 1,
        },
        moves=[NORMAL_MOVES[1], WATER_MOVES[2]],
    ),
    BaseMonster(
        u=96,
        v=0,
        w=32,
        h=32,
        name="チビリュウ",
        type1="ドラゴン",
        type2=None,
        hp=114,
        attack=84,
        defense=70,
        speed=70,
        compatibility={
            "ノーマル": 1,
            "ほのお": 0.5,
            "みず": 0.5,
            "くさ": 0.5,
            "ひこう": 1,
            "ドラゴン": 2,
            "どく": 1,
        },
        moves=[NORMAL_MOVES[0], DRAGON_MOVES[0]],
    ),
    BaseMonster(
        u=96,
        v=32,
        w=32,
        h=32,
        name="シロリュー",
        type1="ドラゴン",
        type2=None,
        hp=136,
        attack=104,
        defense=90,
        speed=90,
        compatibility={
            "ノーマル": 1,
            "ほのお": 0.5,
            "みず": 0.5,
            "くさ": 0.5,
            "ひこう": 1,
            "ドラゴン": 2,
            "どく": 1,
        },
        moves=[NORMAL_MOVES[0], DRAGON_MOVES[1]],
    ),
    BaseMonster(
        u=96,
        v=64,
        w=32,
        h=32,
        name="ウミリュー",
        type1="ドラゴン",
        type2="ひこう",
        hp=166,
        attack=154,
        defense=120,
        speed=100,
        compatibility={
            "ノーマル": 1,
            "ほのお": 0.5,
            "みず": 0.5,
            "くさ": 0.25,
            "ひこう": 1,
            "ドラゴン": 2,
            "どく": 1,
        },
        moves=[NORMAL_MOVES[1], DRAGON_MOVES[2], FLY_MOVES[0], FLY_MOVES[1]],
    ),
    BaseMonster(
        u=128,
        v=0,
        w=32,
        h=32,
        name="トトロン",
        type1="ノーマル",
        type2=None,
        hp=235,
        attack=130,
        defense=130,
        speed=50,
        compatibility={
            "ノーマル": 1,
            "ほのお": 1,
            "みず": 1,
            "くさ": 1,
            "ひこう": 1,
            "ドラゴン": 1,
            "どく": 1,
        },
        moves=[NORMAL_MOVES[1], FIRE_MOVES[2], WATER_MOVES[1], GRASS_MOVES[1]],
    ),
]
